/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MaisonRouteImport } from './routes/maison'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProtectedImport } from './routes/admin._protected'
import { Route as AdminProtectedIndexImport } from './routes/admin._protected.index'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonRoute = MaisonRouteImport.update({
  id: '/maison',
  path: '/maison',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminProtectedRoute = AdminProtectedImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminProtectedIndexRoute = AdminProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)

const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/maison': typeof MaisonRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/maison': typeof MaisonRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/_protected/': typeof AdminProtectedIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/maison': typeof MaisonRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/boutique'
    | '/commande'
    | '/contact'
    | '/maison'
    | '/panier'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/boutique'
    | '/commande'
    | '/contact'
    | '/maison'
    | '/panier'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin/_protected'
    | '/admin/_protected/'
    | '/admin/login'
    | '/boutique'
    | '/commande'
    | '/contact'
    | '/maison'
    | '/panier'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CommandeRoute: typeof CommandeRoute
  ContactRoute: typeof ContactRoute
  MaisonRoute: typeof MaisonRoute
  PanierRoute: typeof PanierRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison': {
      id: '/maison'
      path: '/maison'
      fullPath: '/maison'
      preLoaderRoute: typeof MaisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexImport
      parentRoute: typeof AdminProtectedImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BoutiqueRoute: BoutiqueRoute,
  CommandeRoute: CommandeRoute,
  ContactRoute: ContactRoute,
  MaisonRoute: MaisonRoute,
  PanierRoute: PanierRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}

interface AdminProtectedRouteChildren {
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
